apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv # name of PVC essential for identifying the storage data
  labels:
    app: mysql
    tier: database
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
